eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:
  zipkin:
    base-url: http://localhost:8100
  sleuth:
    sampler:
      percentage: 0.1
feign:
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true

